theme: jekyll-theme-cayman
title: Jordan Faas-Bush
description: Programmer/Game Developer
plugins:
  - jekyll-feed
author:
  name: Jordan Faas-Bush
feed:
  categories:
    - toothpike
    - changelogs
    - load_roll_die
    - new_games
  collections:
    in_game:
      path: "/in_game.atom"
      categories:
        - toothpike
        - changelogs
        - load_roll_die
        - new_games
